backend:
  name: github
  repo: lapadulamichael/groupedmrsite
  branch: main
  base_url: https://groupedmrsite-cms-oauth.vercel.app/

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "jobs"
    label: "Offres d’emploi"
    folder: "content/jobs"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Lieu", name: "location", widget: "string", required: false }
      - { label: "Type", name: "type", widget: "string", required: false }
      - { label: "Résumé", name: "summary", widget: "text", required: false }
      - { label: "Description", name: "description", widget: "markdown", required: false }
      - { label: "Email pour postuler", name: "apply_email", widget: "string" }
      - { label: "Actif", name: "active", widget: "boolean", default: true }